// services/order-service/order_manager.js
// Order lifecycle management & automated replenishment logic for SmartShelf

const http = require("http");
const crypto = require("crypto");
const { logger, queue } = require("../shared");

const VALID_STATUSES = ["PENDING", "SUBMITTED", "SHIPPED", "DELIVERED", "CANCELLED"];

function httpGetJson(url) {
  return new Promise((resolve, reject) => {
    http.get(url, (res) => {
      let data = "";
      res.on("data", (chunk) => (data += chunk));
      res.on("end", () => {
        try {
          resolve({ status: res.statusCode, body: JSON.parse(data) });
        } catch (_) {
          resolve({ status: res.statusCode, body: null });
        }
      });
    }).on("error", reject);
  });
}

function generateOrderId() {
  const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  const randomSuffix = crypto.randomBytes(3).toString("hex").toUpperCase();
  return `ORD-${dateStr}-${randomSuffix}`;
}

/**
 * Creates an order directly
 */
async function createOrder(db, { store_id, product_id, quantity, source = "manual", notes = "", unit_price = 2.5 }) {
  if (!store_id || !product_id || typeof quantity !== "number" || quantity <= 0) {
    throw new Error("Invalid order parameters: store_id, product_id, and positive quantity required");
  }

  const product = await db.collection("products").findOne({ product_id });
  const productName = product ? product.name : "Unknown Product";
  const price = product && product.unit_price ? product.unit_price : unit_price;
  const totalCost = parseFloat((quantity * price).toFixed(2));

  const orderDoc = {
    order_id: generateOrderId(),
    store_id,
    product_id,
    product_name: productName,
    quantity,
    unit_price: price,
    total_cost: totalCost,
    status: "PENDING",
    source,
    notes,
    created_at: new Date(),
    updated_at: new Date(),
  };

  await db.collection("orders").insertOne(orderDoc);
  logger.info("Order created", { order_id: orderDoc.order_id, product_id, quantity, totalCost });

  // Dispatch to order events queue
  const orderEventsQueue = process.env.SQS_ORDER_EVENTS_QUEUE_URL || "smartshelf-order-events-queue";
  await queue.sendMessage(orderEventsQueue, {
    event_type: "ORDER_CREATED",
    order: orderDoc,
    timestamp: new Date().toISOString(),
  });

  return orderDoc;
}

/**
 * Creates an automated replenishment order triggered by low-stock threshold
 * Checks for existing active orders to prevent duplicate orders.
 */
async function createReplenishmentOrder(db, { store_id, product_id, forecastServiceUrl = "http://localhost:3002" }) {
  // 1. Duplicate check: prevent creating multiple open orders for the same SKU & Store
  const existingActive = await db.collection("orders").findOne({
    store_id,
    product_id,
    status: { $in: ["PENDING", "SUBMITTED", "SHIPPED"] },
  });

  if (existingActive) {
    logger.warn("Active replenishment order already exists, suppressing duplicate", {
      order_id: existingActive.order_id,
      product_id,
      status: existingActive.status,
    });
    return {
      duplicate: true,
      message: `Active order ${existingActive.order_id} already exists for ${product_id} with status ${existingActive.status}`,
      existingOrder: existingActive,
    };
  }

  // 2. Fetch optimal order quantity from Forecast Service (/eoq)
  let recommendedQty = 50;
  let eoqData = null;

  try {
    const eoqUrl = `${forecastServiceUrl}/eoq/${store_id}/${product_id}`;
    const resp = await httpGetJson(eoqUrl);
    if (resp.status === 200 && resp.body && resp.body.eoq && resp.body.eoq.optimalOrderQty) {
      recommendedQty = resp.body.eoq.optimalOrderQty;
      eoqData = resp.body.eoq;
      logger.info("Fetched optimal EOQ from Forecast Service", { product_id, recommendedQty });
    }
  } catch (err) {
    logger.warn("Failed to reach Forecast Service, using fallback quantity", { error: err.message });
    const product = await db.collection("products").findOne({ product_id });
    const pack = product && product.case_pack_size ? product.case_pack_size : 12;
    recommendedQty = pack * 6; // default 6 case packs
  }

  // 3. Create the replenishment order
  const orderDoc = await createOrder(db, {
    store_id,
    product_id,
    quantity: recommendedQty,
    source: "automated_eoq_replenishment",
    notes: eoqData
      ? `Generated by EOQ Wilson Formula (Raw: ${eoqData.rawEoq}, Pack Size: ${eoqData.casePackSize})`
      : "Generated by automated replenishment rule",
  });

  return { duplicate: false, order: orderDoc };
}

/**
 * Updates order status and automatically credits inventory on DELIVERED
 */
async function updateOrderStatus(db, order_id, newStatus) {
  if (!VALID_STATUSES.includes(newStatus)) {
    throw new Error(`Invalid status: ${newStatus}. Valid statuses are: ${VALID_STATUSES.join(", ")}`);
  }

  const order = await db.collection("orders").findOne({ order_id });
  if (!order) {
    return null;
  }

  const oldStatus = order.status;
  await db.collection("orders").updateOne(
    { order_id },
    {
      $set: {
        status: newStatus,
        updated_at: new Date(),
        ...(newStatus === "DELIVERED" ? { delivered_at: new Date() } : {}),
      },
    }
  );

  logger.info("Order status updated", { order_id, oldStatus, newStatus });

  // If transitioned to DELIVERED, automatically restock inventory in MongoDB Atlas!
  if (newStatus === "DELIVERED" && oldStatus !== "DELIVERED") {
    await db.collection("inventory_status").updateOne(
      { store_id: order.store_id, product_id: order.product_id },
      {
        $inc: { on_hand_qty: order.quantity },
        $set: {
          last_updated: new Date(),
          last_restocked_order: order_id,
          last_sensor: "delivery_restock",
        },
      },
      { upsert: true }
    );

    logger.info("Inventory automatically restocked upon order delivery", {
      order_id,
      store_id: order.store_id,
      product_id: order.product_id,
      restocked_qty: order.quantity,
    });
  }

  const updatedOrder = await db.collection("orders").findOne({ order_id });
  return updatedOrder;
}

module.exports = {
  createOrder,
  createReplenishmentOrder,
  updateOrderStatus,
};
